name: Veracode Scan

on: [push, pull_request]

env:
  JAVA_WRAPPER_VERSION: "20.3.6.1" # Update the version when new version is released.
  APP_NAME: "Veracode Jenkins Plugin"
  SANDBOX_NAME: "GitHub Open Source Sandbox"

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Trigger Test Automation
      uses: appleboy/gitlab-ci-action@master
      with:
        host: "https://gitlab.laputa.veracode.io"
        token: ${{ secrets.GITLAB_TOKEN }}
        debug: true
        project_id: 2348
        ref: 'master'
      #run: "curl -X POST -F ref=master https://gitlab.laputa.veracode.io/api/v4/projects/2348/trigger/pipeline??private_token=${{ secrets.GITLAB_TOKEN }}"
