name: Veracode Scan

on: [push, pull_request]

env:
  JAVA_WRAPPER_VERSION: "20.3.6.1" # Update the version when new version is released.

jobs:
  scan:

    runs-on: windows-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Download Java Wrapper Version - "$JAVA_WRAPPER_VERSION"
      run: curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/"$JAVA_WRAPPER_VERSION"/vosp-api-wrappers-java-"$JAVA_WRAPPER_VERSION".jar -o VeracodeJavaAPI.jar
    
    - name: Scan with Java Wrapper
      run: java -jar VeracodeJavaAPI.jar -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} -action UploadAndScan -appname "Veracode Jenkins Plugin" -sandboxname "GitLab Sandbox" -createprofile true -createsandbox true -filepath "./target" -include "*.jar" -version 'date +%Y-%m-%d-%H:%M:%S' -pattern "veracode-scan*.jar" -replacement "veracode-scan.jar"
